AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Google Calendar LINE Notifier

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - arm64
    Timeout: 60
    MemorySize: 256

Resources:
  GoogleCalendarLineNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: google-calendar-line-notifier
      CodeUri: .
      Handler: bootstrap
      Description: Google Calendar LINE Notifier Lambda Function
      Environment:
        Variables:
          LOG_LEVEL: "INFO"
          TZ: "Asia/Tokyo"  # Lambda実行環境のタイムゾーンをJSTに設定
          # SSMパラメータは環境変数から参照せず、実行時にSDKで取得する
          SSM_GOOGLE_CREDS_PARAM: "/google-calendar-line-notifier/google-creds"
          SSM_LINE_TOKEN_PARAM: "/google-calendar-line-notifier/line-channel-access-token"
          SSM_LINE_USER_ID_PARAM: "/google-calendar-line-notifier/line-user-id"
          SSM_CALENDAR_ID_PARAM: "/google-calendar-line-notifier/calendar-id"

      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            # 毎朝10:00 JST = 01:00 UTC
            Schedule: cron(0 1 * * ? *)
            Description: Google Calendar LINE Notifier Daily Schedule
            Enabled: true

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/google-calendar-line-notifier/*"

  GoogleCalendarLineNotifierLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/google-calendar-line-notifier"
      RetentionInDays: 30

Outputs:
  GoogleCalendarLineNotifierFunction:
    Description: Google Calendar LINE Notifier Lambda Function ARN
    Value: !GetAtt GoogleCalendarLineNotifierFunction.Arn

  GoogleCalendarLineNotifierFunctionIamRole:
    Description: Implicit IAM Role created for Google Calendar LINE Notifier function
    Value: !GetAtt GoogleCalendarLineNotifierFunctionRole.Arn
